baseURL = "https://tufu8.github.io/Gu_Stack/"
languageCode = "zh-CN"
title = "Gu_WebStack Created by Hugo"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""

[params]
  author = "Gugu"
  description = "Webstack Hugo"
[params.search]
  enable = true
[params.darkmode]
  enable = false